Switch from App.xaml to plain Program.Main(), for Mono
The Travis-CI build reports:

 App.xaml.cs(7,37): error CS0246: The type or namespace name `StartupEventArgs' could not be found. Are you missing an assembly reference?